### ISSUE TITLE
Documentation & Examples

### ISSUE THREAD

**Issue by sholsapp** [mbreese/swalign#1]
This module needs example use cases and documentation. 

I can't figure out how to use it.

**Comment by mostafahasanin** [comment]
when I run the code this error appeared 
ImportError: No module named 'swalign' 
can you help me ?

**Comment by mbreese** [comment]
Can you tell me how you installed and ran it? What command did you type?

--
Marcus

**Comment by mostafahasanin** [comment]
thank you mbreese , I have run the code correctly  
but , I think that the code it's not efficient  
because if the sequence is large it will take more time to run

**Comment by mbreese** [comment]
If the sequences are very large, it will be very inefficient. The library is more useful for quick tests, exploring the alignment algorithms, and small sequences. It’s not really meant for genome-scale work. How big are the sequences?

**Comment by mostafahasanin** [comment]
I am using DNA sequences and it's very large

**Comment by akanksha2016** [comment]
when I run the code this error appeared
ImportError: No module named 'swalign'
on installing : pip install git+https://github.com/mbreese/swalign/
Getting error: could not create '/usr/local/p3_env/lib/python3.5/site-packages/swalign': Permission denied
Can u pls help?

**Comment by mbreese** [comment]
It looks like you don't have permissions to install anything on that computer. You'll either need root permissions to install, or (recommended) install in a user-local directory. 

Look for an option in `pip` like `-u` or `--user`.

**Comment by imsanka** [comment]
Hi,
I am trying to use the swalign to align the amino acids sequences. 
When I ran it, the alignment seems to give the score based on the default matrix. What's the matrix?
If I want to add a new matrix, do you have a recommendation?
Thank you.

Cheers,
IS

**Comment by t0mj0nes** [comment]
The simple examples given do not work out of the box:

AttributeError: module 'swalign' has no attribute 'LocalAlignment'

**Comment by t0mj0nes** [comment]
Follow-up: It works if you manually build/install in the installation directory only (Win10).

How can I capture the output, rather than just sending it to stdout?
