### ISSUE TITLE
AttributeError when constructing a ScoringMatrix from text

### ISSUE THREAD

**Issue by georgeglidden** [mbreese/swalign#15]
I'm using `swalign / 0.3.6 / pyhdfd78af_0 / bioconda` for peptide sequence alignment. When constructing a BLOSUM62 ScoringMatrix object from text (e.g., the contents of [BLOSUM62.txt](https://github.com/mbreese/swalign/files/9658833/BLOSUM62.txt)) I encounter the error:

```File ~/Desktop/peculiar-palindromes/peculiarpalindromes/scoring/peptide.py:17, in BLOSUM62()
     16 def BLOSUM62():
---> 17     return ScoringMatrix(text = BLOSUM62_text())

File ~/miniconda3/envs/peculiar-palindromes/lib/python3.10/site-packages/swalign/__init__.py:30, in ScoringMatrix.__init__(self, filename, text, wildcard_score)
     28     fs = open(filename)
     29 else:
---> 30     fs = StringIO.StringIO(text)
     32 self.scores = []
     33 self.bases = None
```

When line 30 is replaced by `fs = StringIO(text)`, or when I load the matrix from a file, everything works fine.

**Comment by mbreese** [comment]
I’ll take a look, but it might be a missing ‘rt’ argument in the open command.

**Comment by georgeglidden** [comment]
> I’ll take a look, but it might be a missing ‘rt’ argument in the open command.

Where should I include the argument?

**Comment by mbreese** [comment]
You're absolutely right ... (I didn't understand what you were asking originally). fixed in main branch and pushed an update to pypi.
