### ISSUE TITLE
full_query issue

### ISSUE THREAD

**Issue by amberlin** [mbreese/swalign#5]
Hi When I align a short sequence to a long one and use the full_query= True I get an alignment that starts the beginning of the query as expected but expect to the end of the reference instead of ending at the query.  

Sequences:

```
>query
CACCTCCTGTTTGCGGAAGAAA
>ref
tctctgaagatcatgtggcctcagtgaaaaaatcagtctcaagtaaaggccaaccaagccctcgagcagttattcccatgtcctgtataaccaatggaagtggtgcaaacagaaaaccaagtcataccagtgctgtctcaattgcaggaaaagaaactctttcatctgctgctaaaag
```

scoring parameters:
gapextend: -0.5
gapopen: -10.0
match: 5
mismatch: -4

final cigar string
cigar: [(4, 'M'), (2, 'D'), (6, 'M'), (5, 'D'), (4, 'M'), (3, 'D'), (8, 'M'), (22, 'D')]

```
125 TACCAGTGCTGTCTCAATTGCAGGAAAAGAAACTCTTTCATCTGCTGCTAAAAG  178
    .|||  |.||||     ||||   ..||||||                      
1   CACC--TCCTGT-----TTGC---GGAAGAAA----------------------  22
```

It seems that the alignment should end at the last set of matches and not include the last 22bp gap
Also the 3' side of the alignment changes when I turn full_query to False.  I would expect that the alignment would be the same except that the first base is included when full_query is True.

```
126 ACCAGTGCTGTCTCAATTGCAGGAAAAGA   154
    |||  |.||||     |||| ||||.|.|
2   ACC--TCCTGT-----TTGC-GGAAGAAA   22
```

**Comment by mbreese** [comment]
What command line / method call are you using? I wonder if the query and ref sequences aren’t getting assigned in the right order. If I remember correctly, the query should be on top for the alignment output.

Marcus

**Comment by amberlin** [comment]
The sequences are assigned correctly.  It is my printing that is upside down.

Here are the methods I am calling 
```
score_matrix = swalign.NucleotideScoringMatrix(match=self.match, mismatch=self.mismatch)
self.local_aligner = swalign.LocalAlignment(score_matrix, gap_penalty=self.gapopen,
                                                    gap_extension_penalty=self.gapextend, full_query=full_query)

```
and then
```
alignment = self.local_aligner.align(tmp_sequence, query_sequence, rc=(seq_dir == 'reverse'))
```
